### ISSUE TITLE
 Too few arguments to function React\Socket\Server::__construct()

### ISSUE THREAD

**Issue by NeroAdvents** [rapsspider/cake_ratchet#1]
Hi,

I'm trying to use your plugin on my CakePHP project (v3.8.13) and it seems to have some issues when using **bin/cake ratchet start** command.
```
Exception: Too few arguments to function React\Socket\Server::__construct(), 1 passed in /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/rapsspider/cake_ratchet/src/Shell/RatchetShell.php on line 47 and at least 2 expected in [/home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/react/socket/src/Server.php, line 13]
2020-08-07 13:21:31 Error: [ArgumentCountError] Too few arguments to function React\Socket\Server::__construct(), 1 passed in /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/rapsspider/cake_ratchet/src/Shell/RatchetShell.php on line 47 and at least 2 expected in /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/react/socket/src/Server.php on line 13
Stack Trace:
#0 /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/rapsspider/cake_ratchet/src/Shell/RatchetShell.php(47): React\Socket\Server->__construct()
#1 /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/cakephp/cakephp/src/Console/Shell.php(511): CakeRatchet\Shell\RatchetShell->start()
#2 /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/cakephp/cakephp/src/Console/CommandRunner.php(385): Cake\Console\Shell->runCommand()
#3 /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell()
#4 /home/nordine/PhpstormProjects/Websockets/Cake_Ratchet/cakephp/cms/bin/cake.php(12): Cake\Console\CommandRunner->run()
#5 {main}
```
I don't know how to fix this issues. If you could help me on this one.
Thx

**Comment by rapsspider** [comment]
Yo,

J'allais répondre en anglais, mais en français ça sera plus simple :).
Ce projet est hyper vieux, je testais le websocket et j'avais essayé de câbler ça à cakephp (que je n'utilise plus depuis 2015).
Le premier problème est lié au fait que Ratchet et ZMQ ont évolué, et ce projet, pas du tout :).

Je suis dans l'incapacité de déboguer le projet :'(. Par contre, tu peux essayer de prendre les fichiers, le mettre dans ton projet, et l'adapter.

Je pense qu'il faut adapter le fichier https://github.com/rapsspider/cake_ratchet/blob/master/src/Shell/RatchetShell.php#L47 avec ce que l'on peut lire ici : http://socketo.me/docs/push#tying_it_together

Je peux faire des modifications, mais sans tester, c'est pas top.

Hésite pas à me tenir au courant :).

Jason

---

Hi,

I was going to answer in English, but in French it will be easier :).
This project is very old, I was testing the websocket and I tried to wire this to cakephp (which I no longer use since 2015).
The first problem is related to the fact that Ratchet and ZMQ have evolved, and this project, not at all :).

I am unable to debug the project: '(. However, you can try to take the files, put it in your project, and adapt it.

I think we need to adapt the file https://github.com/rapsspider/cake_ratchet/blob/master/src/Shell/RatchetShell.php#L47 with what can be read here: http://socketo.me/docs/push#tying_it_together

I can make changes, but without run and test, it's not great.

Jason

**Comment by NeroAdvents** [comment]
Salut :)

Merci pour ta réponse. Je me doutais bien que le plugin n'avait pas été maintenue depuis. 
Du coup entre temps j'ai apporté quelques modifications au serveur en suivant le tutoriel de reactphp [https://github.com/reactphp/socket](url). Je ne sais pas si c'est suffisant, étant assez débutant sur cakephp et les websockets, je ne saurais dire. C'est pourquoi j'essaye d'apprendre à les manipuler  ^^
```
    public function start() {
        $this->__loop = Factory::create();

        $webSock = new Server('0.0.0.0:8080', $this->__loop);
        echo "Listening on {$webSock->getAddress()}\n";
        $webSock->on('connection', function (ConnectionInterface $connection) {
            echo "New connection from user: " . $connection->getRemoteAddress() . "\n";
            $connection->write("Hello " . $connection->getRemoteAddress() . "!\n");
            $connection->write("Welcome to this amazing server!\n");

            $connection->on('data', function ($data) use ($connection) {
                $connection->write(strtoupper($data));
            });
        });
        $this->__loop->run();
    }
```
```
➜  cms git:(master) ✗ ./bin/cake ratchet start
Listening on tcp://0.0.0.0:8080
New connection from user: tcp://127.0.0.1:47384
```
```
➜  cakephp git:(master) ✗ telnet 0.0.0.0 8080
Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
Hello tcp://127.0.0.1:47384!
Welcome to this amazing server!
```
Je te laisse faire les modifications de ton côté ! Notifie-moi le jour où ce sera bon :+1: 
Merci à toi. Bonne journée !

**EDIT**

J'ai une autre petite question sur la création de la partie client dans CakePHP. 
Sais-tu comment procéder et où dois-je coder cette partie (ex : pour faire un chat) ? Je suis un peu perdu sachant que Cake repose sur un autre modèle que celui démontré dans les tutoriels ^^'.
Merci d'avance !
